-- Create the account_type enumeration type
CREATE TYPE account_type AS ENUM ('Client', 'Admin');


-- Table structure for table `account`
CREATE TABLE IF NOT EXISTS public.account
(
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Create account for Tony
INSERT INTO "account" 
(account_firstname, account_lastname, account_email, account_password)
VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');


-- Alter Tony's account type to Admin
UPDATE "account" SET account_type = 'Admin' WHERE account_firstname = 'Tony';

-- Delete Tony file entirely
DELETE FROM "account" WHERE account_firstname = 'Tony';

--Adapt GM Hummer description
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'large interior')
WHERE inv_id = 10;

-- Use INNER JOIN to select fields from inventory and classification tables
SELECT 
    inv_make,
    inv_model,
    class.classification_name
FROM 
    public.inventory AS inv
JOIN 
    public.classification AS class ON inv.classification_id = class.classification_id
WHERE 
    class.classification_name = 'Sport';

-- Update all records in the inventory table to add "/vehicles" to the middle of the file path in the inv_image and inv_thumbnail columns
UPDATE inventory
SET inv_thumbnail = REPLACE(inv_thumbnail, 'images', 'images/vehicles'),
    inv_image = REPLACE(inv_image, 'images', 'images/vehicles');